/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package erp_muzamia.ui;

import erp_muzamia.dao.DaoDetOperacion;
import erp_muzamia.dao.DaoFacturas;
import erp_muzamia.dao.DaoOperacion;
import erp_muzamia.dao.DaoProveedores;
import erp_muzamia.dao.impl.DaoDetOperacionImpl;
import erp_muzamia.dao.impl.DaoFacturasImpl;
import erp_muzamia.dao.impl.DaoOperacionImpl;
import erp_muzamia.dao.impl.DaoProveedoresImpl;
import erp_muzamia.dto.DetOperacion;
import erp_muzamia.dto.Operacion;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CajaUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestosUI
     */
    public CajaUI() {
        initComponents();
        listarCatOperacion();
        listarProveedores();
        listarComprobantes();

        Date date = new Date();
        jdcFechaOpe.setDate(date);
    }

    public void listarCatOperacion() {
        DaoFacturas daoFacturas = new DaoFacturasImpl();
        List<Object[]> list = daoFacturas.lstCatOperacion();

        Object[] row;

        for (int i = 0; i < list.size(); i++) {
            row = new Object[2];
            row = list.get(i);
            jcbCatOperacion.addItem(row[1].toString());
        };
    }

    public void listarProveedores() {
        DaoFacturas daoFacturas = new DaoFacturasImpl();
        List<Object[]> list = daoFacturas.lstProveedores();

        Object[] row;

        for (int i = 0; i < list.size(); i++) {
            row = new Object[4];
            row = list.get(i);
            jcbItems.addItem(row[1].toString());
        };
    }

    public void listarComprobantes() {
        DaoFacturas daoFacturas = new DaoFacturasImpl();
        List<Object[]> list = daoFacturas.lstComprobantes();

        Object[] row;

        for (int i = 0; i < list.size(); i++) {
            row = new Object[3];
            row = list.get(i);
            jcbComprobantes.addItem(row[1].toString());
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdcFechaOpe = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbCatOperacion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbItems = new javax.swing.JComboBox<>();
        jcbComprobantes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfImporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtfConcepto = new javax.swing.JTextField();
        jbRegistrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("CAJA CHICA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jdcFechaOpe.setDateFormatString("yyyy-MM-dd");
        jdcFechaOpe.setMinimumSize(new java.awt.Dimension(120, 22));
        jdcFechaOpe.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Fecha Operación");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Categoria");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcbCatOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCatOperacionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Item");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Comprobante");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcbComprobantes.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nro. de Serie");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField3.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Importe");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Moneda");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soles", "Dolares" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Concepto");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcFechaOpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbCatOperacion, 0, 156, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbItems, 0, 156, Short.MAX_VALUE)
                            .addComponent(jcbComprobantes, 0, 156, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jtfImporte)
                            .addComponent(jtfConcepto))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcFechaOpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jcbCatOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jbRegistrar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        int Ok = JOptionPane.showConfirmDialog(null, "El monto de la operación es " + jtfImporte.getText() + ".\n\n¿Desea registrar la operación?", "Registrar Operación", JOptionPane.YES_NO_OPTION);

        if (Ok == 0) {

            Operacion operacionBE = new Operacion();

            double mnt_pagado = 0.0;
            double mnt_cobrado = 0.0;
            double mnt_saldo = 0.0;

            mnt_pagado = Double.parseDouble(jtfImporte.getText());

            operacionBE.setMpag_id(1);
            operacionBE.setCaja_id(null);
            operacionBE.setUser_id(2);
            operacionBE.setClie_id(null);
            if (jcbCatOperacion.getSelectedIndex() == 0) {
                operacionBE.setProv_id(jcbItems.getSelectedIndex() + 1);
                operacionBE.setTope_id(2);
            } else if (jcbCatOperacion.getSelectedIndex() == 1) {
                operacionBE.setProv_id(null);
                operacionBE.setTope_id(7);
            }
            operacionBE.setOper_timestamp(null);
            operacionBE.setOper_monto(mnt_pagado);
            operacionBE.setOper_pagado(mnt_pagado);
            operacionBE.setOper_vuelto(0.0);
            operacionBE.setOper_cobrado(mnt_cobrado);
            operacionBE.setOper_saldo(mnt_saldo);

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            operacionBE.setOper_fecha(sdf.format(jdcFechaOpe.getDate()));

            DaoOperacion daoOperacion = new DaoOperacionImpl();

            int idOpe = daoOperacion.registrarOperacion(operacionBE);
            DaoDetOperacion daoDetOperacion = new DaoDetOperacionImpl();
            String message = null;

            DetOperacion detOperacionBE = detOperacionBE = new DetOperacion();
            detOperacionBE.setOper_id(idOpe);
            detOperacionBE.setUser_id(5);
            detOperacionBE.setServ_id(null);
            detOperacionBE.setProd_id(null);
            detOperacionBE.setDope_s_p(jtfConcepto.getText());
            detOperacionBE.setDope_precio(mnt_pagado);
            detOperacionBE.setDope_cantidad(1);
            detOperacionBE.setDope_subtotal(mnt_pagado);
            detOperacionBE.setDope_descuento(0.0);
            detOperacionBE.setDope_total(mnt_pagado);
            detOperacionBE.setDope_timestamp(null);
            message = daoDetOperacion.registrarDetOperacion(detOperacionBE);

            if (message == null && idOpe > 0) {
                JOptionPane.showMessageDialog(null, "Operación registrada satisfactoriamente.", "En hora buena!", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        return;
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jcbCatOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCatOperacionActionPerformed
        if (jcbCatOperacion.getSelectedIndex() == 0) {
            jcbItems.setEnabled(true);
        } else if (jcbCatOperacion.getSelectedIndex() == 1) {
            jcbItems.setEnabled(false);
        }
    }//GEN-LAST:event_jcbCatOperacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbCatOperacion;
    private javax.swing.JComboBox<String> jcbComprobantes;
    private javax.swing.JComboBox<String> jcbItems;
    private com.toedter.calendar.JDateChooser jdcFechaOpe;
    private javax.swing.JTextField jtfConcepto;
    private javax.swing.JTextField jtfImporte;
    // End of variables declaration//GEN-END:variables
}
