/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package erp_muzamia.ui;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import erp_muzamia.dao.DaoCategorias;
import erp_muzamia.dao.DaoServicios;
import erp_muzamia.dao.impl.DaoCategoriasImpl;
import erp_muzamia.dao.impl.DaoServiciosImpl;
import erp_muzamia.dto.Categorias;
import erp_muzamia.dto.Servicios;

/**
 *
 * @author User
 */
public class CatalogoUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CatalogoUI
     */
    public CatalogoUI() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (Exception e) {
        }
        doubleClickEvent(jtblServicios);
        listarData();
        listarColumnasTabla();
        listarCategorias();
    }

    public void doubleClickEvent(JTable table) {
        table.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    String id = table.getModel().getValueAt(row, 0).toString();
                    System.out.println("Fila seleccionada: " + row + ", id: " + id);
                }
            }
        });
    }

    public void listarColumnasTabla() {
        jtblServicios.getColumnModel().getColumn(0).setMaxWidth(40);
        jtblServicios.getColumnModel().getColumn(0).setMinWidth(40);
        jtblServicios.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(40);
        jtblServicios.getTableHeader().getColumnModel().getColumn(0).setMinWidth(40);

        jtblServicios.getColumnModel().getColumn(1).setMaxWidth(140);
        jtblServicios.getColumnModel().getColumn(1).setMinWidth(140);
        jtblServicios.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(140);
        jtblServicios.getTableHeader().getColumnModel().getColumn(1).setMinWidth(140);

        jtblServicios.getColumnModel().getColumn(2).setMaxWidth(240);
        jtblServicios.getColumnModel().getColumn(2).setMinWidth(240);
        jtblServicios.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(240);
        jtblServicios.getTableHeader().getColumnModel().getColumn(2).setMinWidth(240);

        jtblServicios.getColumnModel().getColumn(3).setMaxWidth(80);
        jtblServicios.getColumnModel().getColumn(3).setMinWidth(80);
        jtblServicios.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(80);
        jtblServicios.getTableHeader().getColumnModel().getColumn(3).setMinWidth(80);

        jtblServicios.getColumnModel().getColumn(4).setMaxWidth(0);
        jtblServicios.getColumnModel().getColumn(4).setMinWidth(0);
        jtblServicios.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(0);
        jtblServicios.getTableHeader().getColumnModel().getColumn(4).setMinWidth(0);
    }

    public void listarData() {
        DaoServicios daoServicios = new DaoServiciosImpl();
        List<Servicios> list = daoServicios.lst_Servicios_3();
        DefaultTableModel model = (DefaultTableModel) jtblServicios.getModel();
        Object[] obj;
        for (Servicios srv : list) {
            obj = new Object[5];
            obj[0] = srv.getServ_id();
            obj[1] = srv.getServ_nombre();
            obj[2] = srv.getServ_descripcion();
            obj[3] = srv.getServ_precio();
            obj[4] = srv.getCate_id();
            model.addRow(obj);
        }
    }
    
    public void listarCategorias() {
        DaoCategorias daoCategorias = new DaoCategoriasImpl();
        List<Categorias> list = daoCategorias.lst_Categorias_2();

        for (int i = 0; i < list.size(); i++) {
            jcboxCategoria.addItem(list.get(i).getCate_descripcion());
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblServicios = new javax.swing.JTable();
        jtxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jcboxCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jtblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "NOMBRE_L", "PRECIO", "CATE_ID"
            }
        ));
        jtblServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblServicios);

        jLabel1.setText("Id:");

        jLabel2.setText("Descripción:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Categoría:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblServiciosMouseClicked
        Point point = evt.getPoint();
        int row = jtblServicios.rowAtPoint(point);
        jtxtId.setText(jtblServicios.getModel().getValueAt(row, 0).toString());
        jtxtNombre.setText(jtblServicios.getModel().getValueAt(row, 1).toString());
        jtxtDescripcion.setText(jtblServicios.getModel().getValueAt(row, 2).toString());
        jtxtPrecio.setText(jtblServicios.getModel().getValueAt(row, 3).toString());
        jcboxCategoria.setSelectedIndex(Integer.parseInt(jtblServicios.getModel().getValueAt(row, 4).toString()) - 1);
    }//GEN-LAST:event_jtblServiciosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcboxCategoria;
    private javax.swing.JTable jtblServicios;
    private javax.swing.JTextField jtxtDescripcion;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPrecio;
    // End of variables declaration//GEN-END:variables
}
