/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package erp_muzamia.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ConfigUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfigUI
     */
    public ConfigUI() {
        initComponents();
//        try {
//            this.setMaximum(true);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage(), "Fatal Error", JOptionPane.ERROR_MESSAGE);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbConfCate = new javax.swing.JButton();
        jbConfProd = new javax.swing.JButton();
        jbConfMetPago = new javax.swing.JButton();
        jbConfTipOperacion = new javax.swing.JButton();
        jbConfPeriodo = new javax.swing.JButton();
        jbConfProveedores = new javax.swing.JButton();
        jbConfPesos = new javax.swing.JButton();
        jbAsigPrecios = new javax.swing.JButton();
        jbConfAlmacenes = new javax.swing.JButton();
        jbConfCompPago = new javax.swing.JButton();
        jbConfMonedas = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONFIGURACIONES");

        jbConfCate.setText("Configurar CATEGORIAS");
        jbConfCate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfCateActionPerformed(evt);
            }
        });

        jbConfProd.setText("Configurar SERVICIOS / PRODUCTOS");
        jbConfProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfProdActionPerformed(evt);
            }
        });

        jbConfMetPago.setText("Configurar METODO DE PAGO");
        jbConfMetPago.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfMetPago.setEnabled(false);

        jbConfTipOperacion.setText("Configurar TIPO DE OPERACION");
        jbConfTipOperacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfTipOperacion.setEnabled(false);

        jbConfPeriodo.setText("Configurar PERIODOS DE FACTURACION");
        jbConfPeriodo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfPeriodo.setEnabled(false);

        jbConfProveedores.setText("Configurar PROVEEDORES");
        jbConfProveedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfProveedoresActionPerformed(evt);
            }
        });

        jbConfPesos.setText("Configurar PESOS");
        jbConfPesos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfPesos.setEnabled(false);
        jbConfPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfPesosActionPerformed(evt);
            }
        });

        jbAsigPrecios.setText("Asignar PRECIOS");
        jbAsigPrecios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAsigPrecios.setEnabled(false);
        jbAsigPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAsigPreciosActionPerformed(evt);
            }
        });

        jbConfAlmacenes.setText("Configurar ALMACENES");
        jbConfAlmacenes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfAlmacenes.setEnabled(false);
        jbConfAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfAlmacenesActionPerformed(evt);
            }
        });

        jbConfCompPago.setText("Configurar COMPROBANTES DE PAGO");
        jbConfCompPago.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfCompPago.setEnabled(false);
        jbConfCompPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfCompPagoActionPerformed(evt);
            }
        });

        jbConfMonedas.setText("Configurar MONEDAS");
        jbConfMonedas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbConfMonedas.setEnabled(false);
        jbConfMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfMonedasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConfProd, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jbConfAlmacenes, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConfCate, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jbConfProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbConfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfTipOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfMetPago, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbConfPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(124, 124, 124)
                            .addComponent(jbConfCompPago, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbAsigPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(124, 124, 124)
                            .addComponent(jbConfMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfCate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfAlmacenes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfCompPago, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAsigPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jbConfMetPago, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbConfTipOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbConfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfCateActionPerformed
        MantCateUI mantCateUI = new MantCateUI();
        mantCateUI.pack();
        mantCateUI.setLocationRelativeTo(null);
        mantCateUI.setVisible(true);
    }//GEN-LAST:event_jbConfCateActionPerformed

    private void jbConfProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfProdActionPerformed
        MantServUI mantServUI = new MantServUI();
        mantServUI.pack();
        mantServUI.setLocationRelativeTo(null);
        mantServUI.setVisible(true);
    }//GEN-LAST:event_jbConfProdActionPerformed

    private void jbConfPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfPesosActionPerformed
//        MantPesoUI mantPesoUI = new MantPesoUI();
//        mantPesoUI.pack();
//        mantPesoUI.setLocationRelativeTo(null);
//        mantPesoUI.setVisible(true);
    }//GEN-LAST:event_jbConfPesosActionPerformed

    private void jbAsigPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAsigPreciosActionPerformed
//        MantPrecioUI mantPrecioUI = new MantPrecioUI();
//        mantPrecioUI.pack();
//        mantPrecioUI.setLocationRelativeTo(null);
//        mantPrecioUI.setVisible(true);
    }//GEN-LAST:event_jbAsigPreciosActionPerformed

    private void jbConfProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfProveedoresActionPerformed
        MantProvUI mantProvUI = new MantProvUI();
        mantProvUI.pack();
        mantProvUI.setLocationRelativeTo(null);
        mantProvUI.setVisible(true);
    }//GEN-LAST:event_jbConfProveedoresActionPerformed

    private void jbConfAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfAlmacenesActionPerformed
//        MantAlmacenUI mantAlmacen = new MantAlmacenUI();
//        mantAlmacen.pack();
//        mantAlmacen.setLocationRelativeTo(null);
//        mantAlmacen.setVisible(true);
    }//GEN-LAST:event_jbConfAlmacenesActionPerformed

    private void jbConfCompPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfCompPagoActionPerformed
//        MantCompUI mantComp = new MantCompUI();
//        mantComp.pack();
//        mantComp.setLocationRelativeTo(null);
//        mantComp.setVisible(true);
    }//GEN-LAST:event_jbConfCompPagoActionPerformed

    private void jbConfMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfMonedasActionPerformed
//        MantMoneUI mantMone = new MantMoneUI();
//        mantMone.pack();
//        mantMone.setLocationRelativeTo(null);
//        mantMone.setVisible(true);
    }//GEN-LAST:event_jbConfMonedasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAsigPrecios;
    private javax.swing.JButton jbConfAlmacenes;
    private javax.swing.JButton jbConfCate;
    private javax.swing.JButton jbConfCompPago;
    private javax.swing.JButton jbConfMetPago;
    private javax.swing.JButton jbConfMonedas;
    private javax.swing.JButton jbConfPeriodo;
    private javax.swing.JButton jbConfPesos;
    private javax.swing.JButton jbConfProd;
    private javax.swing.JButton jbConfProveedores;
    private javax.swing.JButton jbConfTipOperacion;
    // End of variables declaration//GEN-END:variables
}
