/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package erp_muzamia.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import erp_muzamia.dao.DaoOperacion;
import erp_muzamia.dao.DaoReportes;
//import erp_muzamia.dao.DaoMetPago;
import erp_muzamia.dao.DaoUsuarios;
import erp_muzamia.dao.impl.DaoOperacionImpl;
import erp_muzamia.dao.impl.DaoReportesImpl;
//import erp_muzamia.dao.impl.DaoMetPagoImpl;
import erp_muzamia.dao.impl.DaoUsuariosImpl;
import erp_muzamia.dto.Operaciones;
//import erp_muzamia.dto.Metodo_pago;
import erp_muzamia.dto.Usuarios;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author User
 */
public class ReporteVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteVentas
     */
    public ReporteVentas() {
        initComponents();
        lst_data_rep_1();
        lst_data_rep_2();
        lst_data_rep_3();
    }

    public void lst_data_rep_1() {
        DaoReportes daoReportes = new DaoReportesImpl();
        List<Object[]> list = daoReportes.reporte_1();
        DefaultTableModel model = (DefaultTableModel) jtVentas_x_Estilista.getModel();
        model.setRowCount(0);

        Object[] row;

        for (int i = 0; i < list.size(); i++) {
            row = new Object[5];
            row = list.get(i);
            model.addRow(row);
        };
    }

    public void lst_data_rep_2() {
        DaoReportes daoReportes = new DaoReportesImpl();
        List<Object[]> list = daoReportes.reporte_2();
        DefaultTableModel model = (DefaultTableModel) jtTotalVentas_x_Periodo.getModel();
        model.setRowCount(0);

        Object[] row;

        for (int i = 0; i < list.size(); i++) {
            row = new Object[3];
            row = list.get(i);
            model.addRow(row);
        };
    }

    public void lst_data_rep_3() {
        DaoReportes daoReportes = new DaoReportesImpl();
        List<Object[]> list = daoReportes.reporte_3();
        DefaultTableModel model = (DefaultTableModel) jtAtenciones_x_Cliente.getModel();
        model.setRowCount(0);

        Object[] row;

        for (int i = 0; i < list.size(); i++) {
            row = new Object[4];
            row = list.get(i);
            model.addRow(row);
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVentas_x_Estilista = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTotalVentas_x_Periodo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtAtenciones_x_Cliente = new javax.swing.JTable();

        setClosable(true);
        setTitle("REPORTE DE OPERACIONES");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtVentas_x_Estilista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user_id", "Nombres", "Apellidos", "Total", "Periodo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtVentas_x_Estilista);

        jtTotalVentas_x_Periodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "peri_id", "Periodo", "Total Ventas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtTotalVentas_x_Periodo);

        jtAtenciones_x_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. Atenc.", "clie_id", "Nombres", "Apellidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtAtenciones_x_Cliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtAtenciones_x_Cliente;
    private javax.swing.JTable jtTotalVentas_x_Periodo;
    private javax.swing.JTable jtVentas_x_Estilista;
    // End of variables declaration//GEN-END:variables
}
